/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type AskAuthor = {
  _id: string;
  _type: 'askAuthor';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  providerId?: string;
  kind?: 'anonymous' | 'github' | 'google' | 'dev';
  name?: string;
  email?: string;
  lastSeenAt?: string;
};

export type AskBan = {
  _id: string;
  _type: 'askBan';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  providerId?: string;
  kind?: 'anonymous' | 'github' | 'google' | 'dev';
  name?: string;
  email?: string;
  ipHash?: string;
  reason?: string;
  bannedAt?: string;
};

export type QuestionReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'question';
};

export type Question = {
  _id: string;
  _type: 'question';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  body?: string;
  status?: 'pending' | 'published' | 'hidden' | 'spam';
  thread?: QuestionReference;
  slug?: Slug;
  author?: {
    kind?: 'anonymous' | 'github' | 'google' | 'dev';
    name?: string;
    providerId?: string;
    avatarUrl?: string;
    avatarSeed?: string;
  };
  submittedAt?: string;
  publishedAt?: string;
  editedAt?: string;
  deletedAt?: string;
  reactions?: Array<{
    emoji?: 'thumbsup' | 'heart' | 'laugh' | 'party' | 'surprised' | 'pray';
    providerId?: string;
    _type: 'reaction';
    _key: string;
  }>;
  moderation?: {
    heuristicsScore?: number;
    botid?: string;
    ipHash?: string;
    elapsedMs?: number;
  };
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Education = {
  _id: string;
  _type: 'education';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  institution?: string;
  degree?: string;
  location?: string;
  startYear?: number;
  endYear?: number;
  score?: string;
  order?: number;
};

export type SkillGroup = {
  _id: string;
  _type: 'skillGroup';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  items?: Array<string>;
  order?: number;
};

export type Update = {
  _id: string;
  _type: 'update';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  text?: string;
  category?: 'project' | 'work' | 'site' | 'learning' | 'life';
  link?: string;
};

export type Now = {
  _id: string;
  _type: 'now';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<{
    text?: string;
    link?: string;
    _key: string;
  }>;
  updatedAt?: string;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  tagline?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  stack?: Array<string>;
  github?: string;
  live?: string;
  featured?: boolean;
  status?: 'active' | 'maintained' | 'archived' | 'wip';
  year?: number;
  order?: number;
};

export type ExperienceReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'experience';
};

export type Experience = {
  _id: string;
  _type: 'experience';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  companyUrl?: string;
  companyBlurb?: string;
  title?: string;
  location?: string;
  remote?: boolean;
  employmentType?: 'Full-time' | 'Part-time' | 'Contract' | 'Freelance';
  startDate?: string;
  endDate?: string;
  endNote?: string;
  continuedInto?: ExperienceReference;
  continuationNote?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  highlights?: Array<string>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Profile = {
  _id: string;
  _type: 'profile';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  headline?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  availability?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  location?: string;
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  resumeNote?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AskAuthor
  | AskBan
  | QuestionReference
  | Question
  | Slug
  | Education
  | SkillGroup
  | Update
  | Now
  | Project
  | ExperienceReference
  | Experience
  | SanityImageAssetReference
  | Profile
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/ask/queries.ts
// Variable: ASK_THREAD_PAGE_QUERY
// Query: {  "total": count(*[_type == "question" && !defined(thread) && status == "published"]),  "threads": *[_type == "question" && !defined(thread) && status == "published"]{    _id,    "slug": slug.current,    body,    submittedAt,    "author": author{kind, name, avatarUrl, avatarSeed, "isOwner": providerId in $ownerIds},    "replyCount": count(*[_type == "question" && thread._ref == ^._id && status == "published"]),    "lastActivityAt": coalesce(      *[_type == "question" && thread._ref == ^._id && status == "published"] | order(submittedAt desc)[0].submittedAt,      submittedAt    )  } | order(lastActivityAt desc)[$start...$end]}
export type ASK_THREAD_PAGE_QUERY_RESULT = {
  total: number;
  threads: Array<{
    _id: string;
    slug: string | null;
    body: string | null;
    submittedAt: string | null;
    author: {
      kind: 'anonymous' | 'dev' | 'github' | 'google' | null;
      name: string | null;
      avatarUrl: string | null;
      avatarSeed: string | null;
      isOwner: boolean | null;
    } | null;
    replyCount: number;
    lastActivityAt: string | null;
  }>;
};

// Source: src/lib/ask/queries.ts
// Variable: ASK_THREAD_QUERY
// Query: *[_type == "question" && !defined(thread) && status == "published" && slug.current == $slug][0]{    _id,    "slug": slug.current,    submittedAt,    body,    editedAt,    deletedAt,    "author": author{kind, name, avatarUrl, avatarSeed, "isOwner": providerId in $ownerIds},    "reactions": reactions[].emoji,    "replies": *[_type == "question" && thread._ref == ^._id && status == "published"] | order(submittedAt asc){      _id,      body,      submittedAt,      editedAt,      deletedAt,      "author": author{kind, name, avatarUrl, avatarSeed, "isOwner": providerId in $ownerIds},      "isThreadAuthor": author.providerId == ^.author.providerId,      "reactions": reactions[].emoji    }  }
export type ASK_THREAD_QUERY_RESULT = {
  _id: string;
  slug: string | null;
  submittedAt: string | null;
  body: string | null;
  editedAt: string | null;
  deletedAt: string | null;
  author: {
    kind: 'anonymous' | 'dev' | 'github' | 'google' | null;
    name: string | null;
    avatarUrl: string | null;
    avatarSeed: string | null;
    isOwner: boolean | null;
  } | null;
  reactions: Array<
    'heart' | 'laugh' | 'party' | 'pray' | 'surprised' | 'thumbsup' | null
  > | null;
  replies: Array<{
    _id: string;
    body: string | null;
    submittedAt: string | null;
    editedAt: string | null;
    deletedAt: string | null;
    author: {
      kind: 'anonymous' | 'dev' | 'github' | 'google' | null;
      name: string | null;
      avatarUrl: string | null;
      avatarSeed: string | null;
      isOwner: boolean | null;
    } | null;
    isThreadAuthor: boolean | false | true;
    reactions: Array<
      'heart' | 'laugh' | 'party' | 'pray' | 'surprised' | 'thumbsup' | null
    > | null;
  }>;
} | null;

// Source: src/lib/ask/queries.ts
// Variable: ASK_THREAD_INDEX_QUERY
// Query: *[_type == "question" && !defined(thread) && status == "published"]{    "slug": slug.current,    body,    "lastActivityAt": coalesce(      *[_type == "question" && thread._ref == ^._id && status == "published"] | order(submittedAt desc)[0].submittedAt,      submittedAt    )  } | order(lastActivityAt desc)
export type ASK_THREAD_INDEX_QUERY_RESULT = Array<{
  slug: string | null;
  body: string | null;
  lastActivityAt: string | null;
}>;

// Source: src/lib/ask/queries.ts
// Variable: ASK_PENDING_COUNT_QUERY
// Query: count(*[_type == "question" && status == "pending"])
export type ASK_PENDING_COUNT_QUERY_RESULT = number;

// Source: src/lib/ask/queries.ts
// Variable: ASK_REPLY_TARGET_QUERY
// Query: *[_type == "question" && !defined(thread) && status == "published" && slug.current == $slug][0]{_id}
export type ASK_REPLY_TARGET_QUERY_RESULT = {
  _id: string;
} | null;

// Source: src/lib/ask/queries.ts
// Variable: ASK_ACTIVITY_QUERY
// Query: {  "banned": count(*[_type == "askBan" && (providerId == $providerId || ipHash == $ipHash)]) > 0,  "questionsToday": count(*[_type == "question" && !defined(thread) && author.providerId == $providerId && submittedAt > $dayAgo]),  "repliesLastHour": count(*[_type == "question" && defined(thread) && author.providerId == $providerId && submittedAt > $hourAgo]),  "heldNow": count(*[_type == "question" && author.providerId == $providerId && status in ["pending", "spam"]]),  "postsToday": count(*[_type == "question" && author.providerId == $providerId && submittedAt > $dayAgo]),  "postsTodayByIp": count(*[_type == "question" && moderation.ipHash == $ipHash && submittedAt > $dayAgo]),  "duplicate": *[    _type == "question" &&    author.providerId == $providerId &&    coalesce(thread._ref, "") == $threadId &&    body == $body &&    submittedAt > $hourAgo  ][0]{    _id,    status,    body,    submittedAt,    "slug": slug.current,    "name": author.name,    "avatarSeed": author.avatarSeed  }}
export type ASK_ACTIVITY_QUERY_RESULT = {
  banned: boolean;
  questionsToday: number;
  repliesLastHour: number;
  heldNow: number;
  postsToday: number;
  postsTodayByIp: number;
  duplicate: {
    _id: string;
    status: 'hidden' | 'pending' | 'published' | 'spam' | null;
    body: string | null;
    submittedAt: string | null;
    slug: string | null;
    name: string | null;
    avatarSeed: string | null;
  } | null;
};

// Source: src/lib/ask/queries.ts
// Variable: ASK_MESSAGE_QUERY
// Query: *[_type == "question" && _id == $id][0]{    _id,    submittedAt,    deletedAt,    "providerId": author.providerId,    "visible": status == "published" && coalesce(thread->status, "published") == "published",    "banned": count(*[_type == "askBan" && providerId == $providerId]) > 0  }
export type ASK_MESSAGE_QUERY_RESULT = {
  _id: string;
  submittedAt: string | null;
  deletedAt: string | null;
  providerId: string | null;
  visible: false | true;
  banned: boolean;
} | null;

// Source: src/lib/ask/queries.ts
// Variable: ASK_VIEWER_QUERY
// Query: {  "thread": *[_type == "question" && !defined(thread) && status == "published" && slug.current == $slug][0]{    "slug": slug.current,    "messages": *[_type == "question" && (_id == ^._id || thread._ref == ^._id)]{      _id,      body,      status,      submittedAt,      deletedAt,      "providerId": author.providerId,      "name": author.name,      "avatarSeed": author.avatarSeed,      "reacted": reactions[providerId == $providerId].emoji    }  },  "heldQuestions": *[    _type == "question" && !defined(thread) && author.providerId == $providerId && status in ["pending", "spam"]  ] | order(submittedAt desc){_id, body, submittedAt, "name": author.name, "avatarSeed": author.avatarSeed}}
export type ASK_VIEWER_QUERY_RESULT = {
  thread: {
    slug: string | null;
    messages: Array<{
      _id: string;
      body: string | null;
      status: 'hidden' | 'pending' | 'published' | 'spam' | null;
      submittedAt: string | null;
      deletedAt: string | null;
      providerId: string | null;
      name: string | null;
      avatarSeed: string | null;
      reacted: Array<
        'heart' | 'laugh' | 'party' | 'pray' | 'surprised' | 'thumbsup' | null
      > | null;
    }>;
  } | null;
  heldQuestions: Array<{
    _id: string;
    body: string | null;
    submittedAt: string | null;
    name: string | null;
    avatarSeed: string | null;
  }>;
};

// Source: src/sanity/lib/queries.ts
// Variable: PROFILE_QUERY
// Query: *[_type == "profile" && _id == "profile"][0]{    _id,    name,    headline,    bio,    availability,    avatar{      asset,      alt,      hotspot,      crop    },    location,    links[]{_key, label, url},    resumeNote  }
export type PROFILE_QUERY_RESULT = {
  _id: 'profile';
  name: string | null;
  headline: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  availability: string | null;
  avatar: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  location: string | null;
  links: Array<{
    _key: string;
    label: string | null;
    url: string | null;
  }> | null;
  resumeNote: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"] | order(coalesce(endDate, "9999-12-31") desc, startDate desc){    _id,    company,    companyUrl,    companyBlurb,    title,    location,    remote,    employmentType,    startDate,    endDate,    endNote,    continuedInto->{      _id,      company,      title    },    "continuedFrom": *[_type == "experience" && continuedInto._ref == ^._id][0]{_id, company, title, continuationNote},    continuationNote,    body,    highlights  }
export type EXPERIENCE_QUERY_RESULT = Array<{
  _id: string;
  company: string | null;
  companyUrl: string | null;
  companyBlurb: string | null;
  title: string | null;
  location: string | null;
  remote: boolean | null;
  employmentType: 'Contract' | 'Freelance' | 'Full-time' | 'Part-time' | null;
  startDate: string | null;
  endDate: string | null;
  endNote: string | null;
  continuedInto: {
    _id: string;
    company: string | null;
    title: string | null;
  } | null;
  continuedFrom: {
    _id: string;
    company: string | null;
    title: string | null;
    continuationNote: string | null;
  } | null;
  continuationNote: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  highlights: Array<string> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(featured desc, order asc, year desc){    _id,    name,    slug,    tagline,    description,    stack,    github,    live,    featured,    status,    year,    order  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  tagline: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  stack: Array<string> | null;
  github: string | null;
  live: string | null;
  featured: boolean | null;
  status: 'active' | 'archived' | 'maintained' | 'wip' | null;
  year: number | null;
  order: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: NOW_QUERY
// Query: *[_type == "now" && _id == "now"][0]{    _id,    items[]{_key, text, link},    updatedAt  }
export type NOW_QUERY_RESULT = {
  _id: 'now';
  items: Array<{
    _key: string;
    text: string | null;
    link: string | null;
  }> | null;
  updatedAt: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: CHANGELOG_QUERY
// Query: *[_type == "update"] | order(date desc){    _id,    date,    text,    category,    link  }
export type CHANGELOG_QUERY_RESULT = Array<{
  _id: string;
  date: string | null;
  text: string | null;
  category: 'learning' | 'life' | 'project' | 'site' | 'work' | null;
  link: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SKILLS_QUERY
// Query: *[_type == "skillGroup"] | order(order asc){    _id,    title,    items,    order  }
export type SKILLS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  items: Array<string> | null;
  order: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: EDUCATION_QUERY
// Query: *[_type == "education"] | order(order asc){    _id,    institution,    degree,    location,    startYear,    endYear,    score,    order  }
export type EDUCATION_QUERY_RESULT = Array<{
  _id: string;
  institution: string | null;
  degree: string | null;
  location: string | null;
  startYear: number | null;
  endYear: number | null;
  score: string | null;
  order: number | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "total": count(*[_type == "question" && !defined(thread) && status == "published"]),\n  "threads": *[_type == "question" && !defined(thread) && status == "published"]{\n    _id,\n    "slug": slug.current,\n    body,\n    submittedAt,\n    "author": author{kind, name, avatarUrl, avatarSeed, "isOwner": providerId in $ownerIds},\n    "replyCount": count(*[_type == "question" && thread._ref == ^._id && status == "published"]),\n    "lastActivityAt": coalesce(\n      *[_type == "question" && thread._ref == ^._id && status == "published"] | order(submittedAt desc)[0].submittedAt,\n      submittedAt\n    )\n  } | order(lastActivityAt desc)[$start...$end]\n}': ASK_THREAD_PAGE_QUERY_RESULT;
    '\n  *[_type == "question" && !defined(thread) && status == "published" && slug.current == $slug][0]{\n    _id,\n    "slug": slug.current,\n    submittedAt,\n    body,\n    editedAt,\n    deletedAt,\n    "author": author{kind, name, avatarUrl, avatarSeed, "isOwner": providerId in $ownerIds},\n    "reactions": reactions[].emoji,\n    "replies": *[_type == "question" && thread._ref == ^._id && status == "published"] | order(submittedAt asc){\n      _id,\n      body,\n      submittedAt,\n      editedAt,\n      deletedAt,\n      "author": author{kind, name, avatarUrl, avatarSeed, "isOwner": providerId in $ownerIds},\n      "isThreadAuthor": author.providerId == ^.author.providerId,\n      "reactions": reactions[].emoji\n    }\n  }\n': ASK_THREAD_QUERY_RESULT;
    '\n  *[_type == "question" && !defined(thread) && status == "published"]{\n    "slug": slug.current,\n    body,\n    "lastActivityAt": coalesce(\n      *[_type == "question" && thread._ref == ^._id && status == "published"] | order(submittedAt desc)[0].submittedAt,\n      submittedAt\n    )\n  } | order(lastActivityAt desc)\n': ASK_THREAD_INDEX_QUERY_RESULT;
    'count(*[_type == "question" && status == "pending"])': ASK_PENDING_COUNT_QUERY_RESULT;
    '\n  *[_type == "question" && !defined(thread) && status == "published" && slug.current == $slug][0]{_id}\n': ASK_REPLY_TARGET_QUERY_RESULT;
    '{\n  "banned": count(*[_type == "askBan" && (providerId == $providerId || ipHash == $ipHash)]) > 0,\n  "questionsToday": count(*[_type == "question" && !defined(thread) && author.providerId == $providerId && submittedAt > $dayAgo]),\n  "repliesLastHour": count(*[_type == "question" && defined(thread) && author.providerId == $providerId && submittedAt > $hourAgo]),\n  "heldNow": count(*[_type == "question" && author.providerId == $providerId && status in ["pending", "spam"]]),\n  "postsToday": count(*[_type == "question" && author.providerId == $providerId && submittedAt > $dayAgo]),\n  "postsTodayByIp": count(*[_type == "question" && moderation.ipHash == $ipHash && submittedAt > $dayAgo]),\n  "duplicate": *[\n    _type == "question" &&\n    author.providerId == $providerId &&\n    coalesce(thread._ref, "") == $threadId &&\n    body == $body &&\n    submittedAt > $hourAgo\n  ][0]{\n    _id,\n    status,\n    body,\n    submittedAt,\n    "slug": slug.current,\n    "name": author.name,\n    "avatarSeed": author.avatarSeed\n  }\n}': ASK_ACTIVITY_QUERY_RESULT;
    '\n  *[_type == "question" && _id == $id][0]{\n    _id,\n    submittedAt,\n    deletedAt,\n    "providerId": author.providerId,\n    "visible": status == "published" && coalesce(thread->status, "published") == "published",\n    "banned": count(*[_type == "askBan" && providerId == $providerId]) > 0\n  }\n': ASK_MESSAGE_QUERY_RESULT;
    '{\n  "thread": *[_type == "question" && !defined(thread) && status == "published" && slug.current == $slug][0]{\n    "slug": slug.current,\n    "messages": *[_type == "question" && (_id == ^._id || thread._ref == ^._id)]{\n      _id,\n      body,\n      status,\n      submittedAt,\n      deletedAt,\n      "providerId": author.providerId,\n      "name": author.name,\n      "avatarSeed": author.avatarSeed,\n      "reacted": reactions[providerId == $providerId].emoji\n    }\n  },\n  "heldQuestions": *[\n    _type == "question" && !defined(thread) && author.providerId == $providerId && status in ["pending", "spam"]\n  ] | order(submittedAt desc){_id, body, submittedAt, "name": author.name, "avatarSeed": author.avatarSeed}\n}': ASK_VIEWER_QUERY_RESULT;
    '\n  *[_type == "profile" && _id == "profile"][0]{\n    _id,\n    name,\n    headline,\n    bio,\n    availability,\n    avatar{\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    location,\n    links[]{_key, label, url},\n    resumeNote\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "experience"] | order(coalesce(endDate, "9999-12-31") desc, startDate desc){\n    _id,\n    company,\n    companyUrl,\n    companyBlurb,\n    title,\n    location,\n    remote,\n    employmentType,\n    startDate,\n    endDate,\n    endNote,\n    continuedInto->{\n      _id,\n      company,\n      title\n    },\n    "continuedFrom": *[_type == "experience" && continuedInto._ref == ^._id][0]{_id, company, title, continuationNote},\n    continuationNote,\n    body,\n    highlights\n  }\n': EXPERIENCE_QUERY_RESULT;
    '\n  *[_type == "project"] | order(featured desc, order asc, year desc){\n    _id,\n    name,\n    slug,\n    tagline,\n    description,\n    stack,\n    github,\n    live,\n    featured,\n    status,\n    year,\n    order\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "now" && _id == "now"][0]{\n    _id,\n    items[]{_key, text, link},\n    updatedAt\n  }\n': NOW_QUERY_RESULT;
    '\n  *[_type == "update"] | order(date desc){\n    _id,\n    date,\n    text,\n    category,\n    link\n  }\n': CHANGELOG_QUERY_RESULT;
    '\n  *[_type == "skillGroup"] | order(order asc){\n    _id,\n    title,\n    items,\n    order\n  }\n': SKILLS_QUERY_RESULT;
    '\n  *[_type == "education"] | order(order asc){\n    _id,\n    institution,\n    degree,\n    location,\n    startYear,\n    endYear,\n    score,\n    order\n  }\n': EDUCATION_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
