/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Education = {
  _id: string;
  _type: 'education';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  institution?: string;
  degree?: string;
  location?: string;
  startYear?: number;
  endYear?: number;
  score?: string;
  order?: number;
};

export type SkillGroup = {
  _id: string;
  _type: 'skillGroup';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  items?: Array<string>;
  order?: number;
};

export type Update = {
  _id: string;
  _type: 'update';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date?: string;
  text?: string;
  category?: 'project' | 'work' | 'site' | 'learning' | 'life';
  link?: string;
};

export type Now = {
  _id: string;
  _type: 'now';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<{
    text?: string;
    link?: string;
    _key: string;
  }>;
  updatedAt?: string;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  tagline?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  stack?: Array<string>;
  github?: string;
  live?: string;
  featured?: boolean;
  status?: 'active' | 'maintained' | 'archived' | 'wip';
  year?: number;
  order?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type ExperienceReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'experience';
};

export type Experience = {
  _id: string;
  _type: 'experience';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  companyUrl?: string;
  companyBlurb?: string;
  title?: string;
  location?: string;
  remote?: boolean;
  employmentType?: 'Full-time' | 'Part-time' | 'Contract' | 'Freelance';
  startDate?: string;
  endDate?: string;
  endNote?: string;
  continuedInto?: ExperienceReference;
  continuationNote?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  highlights?: Array<string>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Profile = {
  _id: string;
  _type: 'profile';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  headline?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  availability?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  location?: string;
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  resumeNote?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Education
  | SkillGroup
  | Update
  | Now
  | Project
  | Slug
  | ExperienceReference
  | Experience
  | SanityImageAssetReference
  | Profile
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: PROFILE_QUERY
// Query: *[_type == "profile" && _id == "profile"][0]{    _id,    name,    headline,    bio,    availability,    avatar{      asset,      alt,      hotspot,      crop    },    location,    links[]{_key, label, url},    resumeNote  }
export type PROFILE_QUERY_RESULT = {
  _id: 'profile';
  name: string | null;
  headline: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  availability: string | null;
  avatar: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  location: string | null;
  links: Array<{
    _key: string;
    label: string | null;
    url: string | null;
  }> | null;
  resumeNote: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"] | order(coalesce(endDate, "9999-12-31") desc, startDate desc){    _id,    company,    companyUrl,    companyBlurb,    title,    location,    remote,    employmentType,    startDate,    endDate,    endNote,    continuedInto->{      _id,      company,      title    },    "continuedFrom": *[_type == "experience" && continuedInto._ref == ^._id][0]{_id, company, title},    continuationNote,    body,    highlights  }
export type EXPERIENCE_QUERY_RESULT = Array<{
  _id: string;
  company: string | null;
  companyUrl: string | null;
  companyBlurb: string | null;
  title: string | null;
  location: string | null;
  remote: boolean | null;
  employmentType: 'Contract' | 'Freelance' | 'Full-time' | 'Part-time' | null;
  startDate: string | null;
  endDate: string | null;
  endNote: string | null;
  continuedInto: {
    _id: string;
    company: string | null;
    title: string | null;
  } | null;
  continuedFrom: {
    _id: string;
    company: string | null;
    title: string | null;
  } | null;
  continuationNote: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  highlights: Array<string> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(featured desc, order asc, year desc){    _id,    name,    slug,    tagline,    description,    stack,    github,    live,    featured,    status,    year,    order  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  tagline: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  stack: Array<string> | null;
  github: string | null;
  live: string | null;
  featured: boolean | null;
  status: 'active' | 'archived' | 'maintained' | 'wip' | null;
  year: number | null;
  order: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: NOW_QUERY
// Query: *[_type == "now" && _id == "now"][0]{    _id,    items[]{_key, text, link},    updatedAt  }
export type NOW_QUERY_RESULT = {
  _id: 'now';
  items: Array<{
    _key: string;
    text: string | null;
    link: string | null;
  }> | null;
  updatedAt: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: CHANGELOG_QUERY
// Query: *[_type == "update"] | order(date desc){    _id,    date,    text,    category,    link  }
export type CHANGELOG_QUERY_RESULT = Array<{
  _id: string;
  date: string | null;
  text: string | null;
  category: 'learning' | 'life' | 'project' | 'site' | 'work' | null;
  link: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SKILLS_QUERY
// Query: *[_type == "skillGroup"] | order(order asc){    _id,    title,    items,    order  }
export type SKILLS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  items: Array<string> | null;
  order: number | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: EDUCATION_QUERY
// Query: *[_type == "education"] | order(order asc){    _id,    institution,    degree,    location,    startYear,    endYear,    score,    order  }
export type EDUCATION_QUERY_RESULT = Array<{
  _id: string;
  institution: string | null;
  degree: string | null;
  location: string | null;
  startYear: number | null;
  endYear: number | null;
  score: string | null;
  order: number | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "profile" && _id == "profile"][0]{\n    _id,\n    name,\n    headline,\n    bio,\n    availability,\n    avatar{\n      asset,\n      alt,\n      hotspot,\n      crop\n    },\n    location,\n    links[]{_key, label, url},\n    resumeNote\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "experience"] | order(coalesce(endDate, "9999-12-31") desc, startDate desc){\n    _id,\n    company,\n    companyUrl,\n    companyBlurb,\n    title,\n    location,\n    remote,\n    employmentType,\n    startDate,\n    endDate,\n    endNote,\n    continuedInto->{\n      _id,\n      company,\n      title\n    },\n    "continuedFrom": *[_type == "experience" && continuedInto._ref == ^._id][0]{_id, company, title},\n    continuationNote,\n    body,\n    highlights\n  }\n': EXPERIENCE_QUERY_RESULT;
    '\n  *[_type == "project"] | order(featured desc, order asc, year desc){\n    _id,\n    name,\n    slug,\n    tagline,\n    description,\n    stack,\n    github,\n    live,\n    featured,\n    status,\n    year,\n    order\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "now" && _id == "now"][0]{\n    _id,\n    items[]{_key, text, link},\n    updatedAt\n  }\n': NOW_QUERY_RESULT;
    '\n  *[_type == "update"] | order(date desc){\n    _id,\n    date,\n    text,\n    category,\n    link\n  }\n': CHANGELOG_QUERY_RESULT;
    '\n  *[_type == "skillGroup"] | order(order asc){\n    _id,\n    title,\n    items,\n    order\n  }\n': SKILLS_QUERY_RESULT;
    '\n  *[_type == "education"] | order(order asc){\n    _id,\n    institution,\n    degree,\n    location,\n    startYear,\n    endYear,\n    score,\n    order\n  }\n': EDUCATION_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
