export const siteConfig = {
  name: 'Hemant Rajput',
  url: 'https://rajputhemant.me',
  nav: [
    { label: 'Work', href: '/work' },
    { label: 'Projects', href: '/projects' },
    { label: 'Now', href: '/now' },
    { label: 'Changelog', href: '/changelog' },
    { label: 'Lab', href: '/lab' },
    { label: 'Ask', href: '/ask' },
  ],
  routes: [
    '/',
    '/work',
    '/projects',
    '/now',
    '/changelog',
    '/resume',
    '/[page].md',
    '/llms.txt',
    '/sitemap.xml',
    '/robots.txt',
    '/opengraph-image',
    '/studio/[[...tool]]',
    '/api/draft-mode/enable',
    '/not-found',
    '/ask',
    '/ask/[slug]',
    '/api/ask',
    '/api/ask/[slug]/reply',
    '/api/ask/messages/[id]',
    '/api/ask/viewer',
    '/api/auth/[...nextauth]',
    '/lab',
    '/lab/[slug]',
  ],
} as const;

export type Route = (typeof siteConfig.routes)[number];
