/**
 * Compiles each edition's tailwind-merge extension
 * (`flavors/<id>/lib/cn-config.ts`) into static merge tables for
 * `cn/engine`, written next to it as `cn-tables.ts`.
 *
 * `extendTailwindMerge` from `cn/config` builds the same tables in the
 * browser, which ships cn's default config and compiler on every page
 * (~27KB gzipped). The precompiled tables plus the engine are about half
 * that and merge identically. `--full` semantics: every class group is kept,
 * so dynamically built class names still merge; no stylesheet is read.
 *
 *   bun run cn:tables
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { compileToSource } from "cn/compiler";
import { defaultConfig, mergeConfigs } from "cn/config";
import type { ConfigExtension } from "cn/config";

import calibre from "../flavors/calibre/lib/cn-config";
import darkroom from "../flavors/darkroom/lib/cn-config";
import drawingSet from "../flavors/drawing-set/lib/cn-config";
import jacquard from "../flavors/jacquard/lib/cn-config";
import maquette from "../flavors/maquette/lib/cn-config";
import minimal from "../flavors/minimal/lib/cn-config";
import mission from "../flavors/mission/lib/cn-config";
import press from "../flavors/press/lib/cn-config";
import surface from "../flavors/surface/lib/cn-config";
import survey from "../flavors/survey/lib/cn-config";
import timetable from "../flavors/timetable/lib/cn-config";

/** Each edition's merge extension, keyed by flavor id. */
export const editionConfigs: Record<string, ConfigExtension> = {
  calibre,
  darkroom,
  "drawing-set": drawingSet,
  jacquard,
  maquette,
  minimal,
  mission,
  press,
  surface,
  survey,
  timetable,
};

const BANNER =
  "// GENERATED by `bun run cn:tables` from ./cn-config.ts. Do not edit.";

/** The `cn-tables.ts` source for one edition's extension. */
export function compileEditionTables(extension: ConfigExtension): string {
  return compileToSource(mergeConfigs(defaultConfig(), extension), {
    lang: "ts",
    banner: BANNER,
  });
}

/** Where an edition's generated tables live. */
export function tablesPath(flavor: string): string {
  return join(
    import.meta.dirname,
    "..",
    "flavors",
    flavor,
    "lib",
    "cn-tables.ts"
  );
}

if (import.meta.main) {
  for (const [flavor, extension] of Object.entries(editionConfigs)) {
    const out = tablesPath(flavor);
    const source = compileEditionTables(extension);
    let current = "";
    try {
      current = readFileSync(out, "utf8");
    } catch {
      // First run: nothing written yet.
    }
    if (current !== source) writeFileSync(out, source);
    console.log(`${current === source ? "unchanged" : "wrote"} ${out}`);
  }
}
